// Curated, kid-relevant emoji set for Eli7's emoji picker + ":" autocomplete.
// Bundled locally (no external CDN - the Pi kiosk has a locked-down
// environment). Each entry carries English + Portuguese (PT-PT) keywords so
// search/autocomplete works in whichever language Diana types in.
//
// Picked for what an 8-year-old actually reaches for: faces, animals, food,
// hearts/stars, activities, nature. Avoids emoji ZWJ sequences (family/skin
// tone combos) since those render least reliably across color emoji fonts.

export const EMOJI_CATEGORIES = [
  { id: 'faces', label: 'Caras', tabIcon: '😀' },
  { id: 'animals', label: 'Animais', tabIcon: '🐶' },
  { id: 'food', label: 'Comida', tabIcon: '🍎' },
  { id: 'hearts', label: 'Corações', tabIcon: '❤️' },
  { id: 'activities', label: 'Atividades', tabIcon: '⚽' },
  { id: 'nature', label: 'Natureza', tabIcon: '🌈' },
]

// [emoji, categoryId, 'english keywords', 'portuguese keywords']
const RAW_EMOJIS = [
  // --- Faces / Smileys ---
  ['😀', 'faces', 'grinning big smile happy', 'sorriso grande feliz'],
  ['😃', 'faces', 'smiley happy joy', 'feliz alegre contente'],
  ['😄', 'faces', 'laughing happy eyes', 'a rir feliz'],
  ['😁', 'faces', 'grin teeth happy', 'sorriso dentes feliz'],
  ['😆', 'faces', 'laughing squint haha', 'a rir gargalhada'],
  ['😅', 'faces', 'sweat smile nervous laugh', 'suor sorriso nervoso'],
  ['🤣', 'faces', 'rolling laughing rofl', 'a rir muito gargalhada'],
  ['😂', 'faces', 'crying laughing tears joy', 'lagrimas de riso'],
  ['🙂', 'faces', 'slight smile', 'sorriso ligeiro'],
  ['🙃', 'faces', 'upside down silly', 'de cabeca para baixo'],
  ['😉', 'faces', 'wink', 'piscar olho'],
  ['😊', 'faces', 'blush smile happy shy', 'corado sorriso feliz'],
  ['😇', 'faces', 'angel halo innocent', 'anjo halo inocente'],
  ['🥰', 'faces', 'love hearts smile', 'apaixonado coracao adorar'],
  ['😍', 'faces', 'heart eyes love', 'olhos coracao amor'],
  ['🤩', 'faces', 'star struck wow amazed', 'estrelas espantado uau'],
  ['😘', 'faces', 'kiss heart blow', 'beijo coracao'],
  ['😗', 'faces', 'kiss whistle', 'beijo assobio'],
  ['☺️', 'faces', 'smiling relaxed', 'sorriso feliz'],
  ['😚', 'faces', 'kiss closed eyes', 'beijo olhos fechados'],
  ['😙', 'faces', 'kiss smiling eyes', 'beijo sorriso'],
  ['😋', 'faces', 'yummy tongue tasty food', 'saboroso lingua delicioso'],
  ['😛', 'faces', 'tongue out playful', 'lingua de fora brincalhao'],
  ['😜', 'faces', 'wink tongue silly', 'piscar lingua parvo'],
  ['🤪', 'faces', 'crazy wild silly zany', 'maluco doido tolo'],
  ['😝', 'faces', 'tongue eyes closed silly', 'lingua olhos fechados'],
  ['🤑', 'faces', 'money mouth rich', 'dinheiro boca rico'],
  ['🤗', 'faces', 'hug hands', 'abraco maos'],
  ['🤭', 'faces', 'giggle oops hand mouth', 'risadinha mao boca'],
  ['🤫', 'faces', 'shh quiet secret', 'psiu silencio segredo'],
  ['🤔', 'faces', 'thinking hmm', 'a pensar hmm'],
  ['🤨', 'faces', 'suspicious raised eyebrow', 'desconfiado sobrancelha'],
  ['😐', 'faces', 'neutral straight face', 'neutro cara seria'],
  ['😑', 'faces', 'expressionless blank', 'sem expressao'],
  ['😶', 'faces', 'no mouth silent', 'sem boca calado'],
  ['🙄', 'faces', 'eye roll annoyed', 'olhos no ar aborrecido'],
  ['😏', 'faces', 'smirk sly', 'sorriso trocista'],
  ['😴', 'faces', 'sleepy zzz sleep', 'sono a dormir'],
  ['🥱', 'faces', 'yawn tired bored', 'bocejo cansado'],
  ['😌', 'faces', 'relieved calm content', 'aliviado calmo'],
  ['🤤', 'faces', 'drool hungry', 'a babar fome'],
  ['😪', 'faces', 'sleepy tear', 'sonolento lagrima'],
  ['😷', 'faces', 'mask sick', 'mascara doente'],
  ['🤒', 'faces', 'thermometer sick fever', 'termometro doente febre'],
  ['🤕', 'faces', 'bandage hurt injured', 'ligadura magoado'],
  ['🥵', 'faces', 'hot sweaty warm', 'calor suor'],
  ['🥶', 'faces', 'cold freezing', 'frio a gelar'],
  ['😵', 'faces', 'dizzy confused', 'tonto confuso'],
  ['🤯', 'faces', 'mind blown shocked', 'explodido chocado'],
  ['😎', 'faces', 'cool sunglasses', 'fixe oculos de sol'],
  ['🥳', 'faces', 'party celebrate birthday', 'festa celebrar aniversario'],
  ['🤠', 'faces', 'cowboy hat', 'chapeu cowboy'],
  ['🥸', 'faces', 'disguise glasses funny', 'disfarce oculos engracado'],
  ['😕', 'faces', 'confused unsure', 'confuso incerto'],
  ['😟', 'faces', 'worried sad', 'preocupado triste'],
  ['😮', 'faces', 'surprised open mouth wow', 'surpreso boca aberta'],
  ['😲', 'faces', 'astonished shocked', 'espantado chocado'],
  ['😳', 'faces', 'flushed embarrassed shy', 'envergonhado atrapalhado'],
  ['🥺', 'faces', 'pleading puppy eyes cute', 'olhos suplicantes fofo'],
  ['😦', 'faces', 'frowning open mouth', 'franzido boca aberta'],
  ['😨', 'faces', 'fearful scared', 'assustado medo'],
  ['😰', 'faces', 'anxious sweat worried', 'ansioso suor preocupado'],
  ['😢', 'faces', 'crying sad tear', 'a chorar triste'],
  ['😭', 'faces', 'sobbing crying loud tears', 'a chorar muito'],
  ['😱', 'faces', 'scream shocked scared', 'grito assustado'],
  ['😡', 'faces', 'angry mad furious red', 'zangado furioso'],
  ['😠', 'faces', 'angry mad', 'zangado bravo'],
  ['👻', 'faces', 'ghost boo halloween', 'fantasma boo'],
  ['🤖', 'faces', 'robot', 'robo'],
  ['👽', 'faces', 'alien', 'alienigena extraterrestre'],
  ['💩', 'faces', 'poop silly funny', 'coco engracado'],
  ['🤡', 'faces', 'clown', 'palhaco'],
  ['😺', 'faces', 'cat smile happy', 'gato sorriso feliz'],
  ['😸', 'faces', 'cat grin happy', 'gato a sorrir'],
  ['😻', 'faces', 'cat heart eyes love', 'gato olhos coracao'],

  // --- Animals ---
  ['🐶', 'animals', 'dog puppy', 'cao cachorro'],
  ['🐕', 'animals', 'dog', 'cao'],
  ['🐩', 'animals', 'poodle dog', 'cao poodle'],
  ['🐺', 'animals', 'wolf', 'lobo'],
  ['🦊', 'animals', 'fox', 'raposa'],
  ['🐱', 'animals', 'cat kitten', 'gato gatinho'],
  ['🐈', 'animals', 'cat', 'gato'],
  ['🦁', 'animals', 'lion', 'leao'],
  ['🐯', 'animals', 'tiger', 'tigre'],
  ['🐅', 'animals', 'tiger', 'tigre'],
  ['🐆', 'animals', 'leopard', 'leopardo'],
  ['🐴', 'animals', 'horse', 'cavalo'],
  ['🐎', 'animals', 'horse running', 'cavalo a correr'],
  ['🦄', 'animals', 'unicorn magic', 'unicornio magico'],
  ['🦓', 'animals', 'zebra', 'zebra'],
  ['🦌', 'animals', 'deer', 'veado'],
  ['🐮', 'animals', 'cow face', 'vaca'],
  ['🐄', 'animals', 'cow', 'vaca'],
  ['🐷', 'animals', 'pig face', 'porco'],
  ['🐖', 'animals', 'pig', 'porco'],
  ['🐽', 'animals', 'pig snout nose', 'focinho de porco'],
  ['🐗', 'animals', 'boar wild pig', 'javali'],
  ['🐭', 'animals', 'mouse', 'rato'],
  ['🐹', 'animals', 'hamster', 'hamster'],
  ['🐰', 'animals', 'rabbit bunny', 'coelho'],
  ['🐇', 'animals', 'rabbit', 'coelho'],
  ['🐿️', 'animals', 'squirrel', 'esquilo'],
  ['🦔', 'animals', 'hedgehog', 'ourico'],
  ['🦇', 'animals', 'bat', 'morcego'],
  ['🐻', 'animals', 'bear', 'urso'],
  ['🐨', 'animals', 'koala', 'coala'],
  ['🐼', 'animals', 'panda', 'panda'],
  ['🦥', 'animals', 'sloth slow', 'preguica lento'],
  ['🦦', 'animals', 'otter', 'lontra'],
  ['🦨', 'animals', 'skunk', 'gamba doninha'],
  ['🦘', 'animals', 'kangaroo', 'canguru'],
  ['🐘', 'animals', 'elephant', 'elefante'],
  ['🦏', 'animals', 'rhino', 'rinoceronte'],
  ['🦛', 'animals', 'hippo', 'hipopotamo'],
  ['🐪', 'animals', 'camel', 'camelo'],
  ['🐫', 'animals', 'camel two humps', 'camelo duas bossas'],
  ['🦒', 'animals', 'giraffe', 'girafa'],
  ['🦙', 'animals', 'llama', 'lama'],
  ['🐐', 'animals', 'goat', 'cabra'],
  ['🐑', 'animals', 'sheep', 'ovelha'],
  ['🐂', 'animals', 'ox bull', 'boi touro'],
  ['🐃', 'animals', 'buffalo', 'bufalo'],
  ['🐵', 'animals', 'monkey', 'macaco'],
  ['🙈', 'animals', 'monkey see no evil covering eyes', 'macaco a tapar olhos'],
  ['🙉', 'animals', 'monkey hear no evil covering ears', 'macaco a tapar orelhas'],
  ['🙊', 'animals', 'monkey speak no evil covering mouth', 'macaco a tapar boca'],
  ['🐔', 'animals', 'chicken hen', 'galinha'],
  ['🐓', 'animals', 'rooster', 'galo'],
  ['🐣', 'animals', 'hatching chick', 'pinto a nascer'],
  ['🐤', 'animals', 'baby chick', 'pintainho'],
  ['🐥', 'animals', 'front facing baby chick', 'pintainho'],
  ['🐧', 'animals', 'penguin', 'pinguim'],
  ['🐦', 'animals', 'bird', 'passaro'],
  ['🕊️', 'animals', 'dove peace bird', 'pomba paz'],
  ['🦆', 'animals', 'duck', 'pato'],
  ['🦅', 'animals', 'eagle', 'aguia'],
  ['🦉', 'animals', 'owl', 'mocho coruja'],
  ['🦚', 'animals', 'peacock', 'pavao'],
  ['🦜', 'animals', 'parrot', 'papagaio'],
  ['🦢', 'animals', 'swan', 'cisne'],
  ['🦩', 'animals', 'flamingo', 'flamingo'],
  ['🦃', 'animals', 'turkey', 'peru'],
  ['🦤', 'animals', 'dodo', 'dodo'],
  ['🐸', 'animals', 'frog', 'sapo ra'],
  ['🐢', 'animals', 'turtle tortoise', 'tartaruga'],
  ['🐍', 'animals', 'snake', 'cobra'],
  ['🦎', 'animals', 'lizard gecko', 'lagarto osga'],
  ['🦖', 'animals', 'dinosaur trex', 'dinossauro trex'],
  ['🦕', 'animals', 'dinosaur brontosaurus', 'dinossauro'],
  ['🐊', 'animals', 'crocodile alligator', 'crocodilo'],
  ['🐳', 'animals', 'whale spout', 'baleia'],
  ['🐋', 'animals', 'whale', 'baleia'],
  ['🐬', 'animals', 'dolphin', 'golfinho'],
  ['🐟', 'animals', 'fish', 'peixe'],
  ['🐠', 'animals', 'tropical fish', 'peixe tropical'],
  ['🐡', 'animals', 'blowfish pufferfish', 'baiacu'],
  ['🦈', 'animals', 'shark', 'tubarao'],
  ['🐙', 'animals', 'octopus', 'polvo'],
  ['🦑', 'animals', 'squid', 'lula'],
  ['🦐', 'animals', 'shrimp', 'camarao'],
  ['🦞', 'animals', 'lobster', 'lagosta'],
  ['🦀', 'animals', 'crab', 'caranguejo'],
  ['🐌', 'animals', 'snail', 'caracol'],
  ['🦋', 'animals', 'butterfly', 'borboleta'],
  ['🐛', 'animals', 'caterpillar bug', 'lagarta'],
  ['🐜', 'animals', 'ant', 'formiga'],
  ['🐝', 'animals', 'bee', 'abelha'],
  ['🐞', 'animals', 'ladybug', 'joaninha'],
  ['🕷️', 'animals', 'spider', 'aranha'],
  ['🕸️', 'animals', 'spider web', 'teia de aranha'],
  ['🦂', 'animals', 'scorpion', 'escorpiao'],
  ['🦟', 'animals', 'mosquito', 'mosquito'],
  ['🦗', 'animals', 'cricket grasshopper', 'grilo gafanhoto'],

  // --- Food ---
  ['🍎', 'food', 'apple', 'maca'],
  ['🍏', 'food', 'green apple', 'maca verde'],
  ['🍊', 'food', 'orange tangerine', 'laranja tangerina'],
  ['🍋', 'food', 'lemon', 'limao'],
  ['🍌', 'food', 'banana', 'banana'],
  ['🍉', 'food', 'watermelon', 'melancia'],
  ['🍇', 'food', 'grapes', 'uvas'],
  ['🍓', 'food', 'strawberry', 'morango'],
  ['🫐', 'food', 'blueberry', 'mirtilo'],
  ['🍈', 'food', 'melon', 'meloa'],
  ['🍒', 'food', 'cherry', 'cereja'],
  ['🍑', 'food', 'peach', 'pessego'],
  ['🥭', 'food', 'mango', 'manga'],
  ['🍍', 'food', 'pineapple', 'ananas'],
  ['🥥', 'food', 'coconut', 'coco'],
  ['🥝', 'food', 'kiwi', 'kiwi'],
  ['🍅', 'food', 'tomato', 'tomate'],
  ['🥑', 'food', 'avocado', 'abacate'],
  ['🥦', 'food', 'broccoli', 'brocolos'],
  ['🥬', 'food', 'lettuce leafy green', 'alface'],
  ['🥒', 'food', 'cucumber', 'pepino'],
  ['🥕', 'food', 'carrot', 'cenoura'],
  ['🌽', 'food', 'corn', 'milho'],
  ['🥔', 'food', 'potato', 'batata'],
  ['🍠', 'food', 'sweet potato', 'batata doce'],
  ['🥐', 'food', 'croissant', 'croissant'],
  ['🍞', 'food', 'bread', 'pao'],
  ['🥖', 'food', 'baguette bread', 'baguete pao'],
  ['🧀', 'food', 'cheese', 'queijo'],
  ['🥚', 'food', 'egg', 'ovo'],
  ['🍳', 'food', 'fried egg', 'ovo estrelado'],
  ['🥞', 'food', 'pancakes', 'panquecas'],
  ['🧇', 'food', 'waffle', 'waffle'],
  ['🥓', 'food', 'bacon', 'bacon toucinho'],
  ['🍗', 'food', 'chicken leg drumstick', 'perna de frango'],
  ['🍔', 'food', 'hamburger burger', 'hamburguer'],
  ['🍟', 'food', 'fries chips', 'batatas fritas'],
  ['🍕', 'food', 'pizza', 'piza pizza'],
  ['🌭', 'food', 'hot dog', 'cachorro quente'],
  ['🥪', 'food', 'sandwich', 'sandes sanduiche'],
  ['🌮', 'food', 'taco', 'taco'],
  ['🌯', 'food', 'burrito', 'burrito'],
  ['🍝', 'food', 'pasta spaghetti', 'massa esparguete'],
  ['🍜', 'food', 'noodles ramen soup', 'macarrao sopa'],
  ['🍲', 'food', 'stew pot soup', 'guisado sopa'],
  ['🍣', 'food', 'sushi', 'sushi'],
  ['🍱', 'food', 'bento lunch box', 'marmita'],
  ['🍤', 'food', 'shrimp tempura', 'camarao'],
  ['🍙', 'food', 'rice ball', 'bola de arroz'],
  ['🍚', 'food', 'rice', 'arroz'],
  ['🍦', 'food', 'ice cream soft', 'gelado'],
  ['🍨', 'food', 'ice cream bowl', 'gelado taca'],
  ['🍧', 'food', 'shaved ice', 'gelo raspado'],
  ['🎂', 'food', 'birthday cake', 'bolo de aniversario'],
  ['🍰', 'food', 'cake slice', 'fatia de bolo'],
  ['🧁', 'food', 'cupcake muffin', 'queque'],
  ['🍮', 'food', 'pudding flan', 'pudim'],
  ['🍭', 'food', 'lollipop', 'chupa chupa'],
  ['🍬', 'food', 'candy sweet', 'rebucado doce'],
  ['🍫', 'food', 'chocolate', 'chocolate'],
  ['🍿', 'food', 'popcorn', 'pipocas'],
  ['🍩', 'food', 'donut doughnut', 'donut rosquinha'],
  ['🍪', 'food', 'cookie biscuit', 'bolacha biscoito'],
  ['🥜', 'food', 'peanuts nuts', 'amendoim'],
  ['🍯', 'food', 'honey', 'mel'],
  ['🥛', 'food', 'milk glass', 'leite'],
  ['🍼', 'food', 'baby bottle', 'biberao'],
  ['☕', 'food', 'coffee', 'cafe'],
  ['🍵', 'food', 'tea', 'cha'],
  ['🧃', 'food', 'juice box', 'sumo'],
  ['🥤', 'food', 'soda drink cup', 'refrigerante copo'],

  // --- Hearts / Stars ---
  ['❤️', 'hearts', 'red heart love', 'coracao vermelho amor'],
  ['🧡', 'hearts', 'orange heart', 'coracao laranja'],
  ['💛', 'hearts', 'yellow heart', 'coracao amarelo'],
  ['💚', 'hearts', 'green heart', 'coracao verde'],
  ['💙', 'hearts', 'blue heart', 'coracao azul'],
  ['💜', 'hearts', 'purple heart', 'coracao roxo'],
  ['🖤', 'hearts', 'black heart', 'coracao preto'],
  ['🤍', 'hearts', 'white heart', 'coracao branco'],
  ['🤎', 'hearts', 'brown heart', 'coracao castanho'],
  ['💔', 'hearts', 'broken heart sad', 'coracao partido'],
  ['❣️', 'hearts', 'heart exclamation', 'coracao exclamacao'],
  ['💕', 'hearts', 'two hearts love', 'dois coracoes'],
  ['💞', 'hearts', 'revolving hearts', 'coracoes a girar'],
  ['💓', 'hearts', 'beating heart', 'coracao a bater'],
  ['💗', 'hearts', 'growing heart', 'coracao a crescer'],
  ['💖', 'hearts', 'sparkling heart', 'coracao brilhante'],
  ['💘', 'hearts', 'heart arrow cupid', 'coracao flecha'],
  ['💝', 'hearts', 'heart gift ribbon', 'coracao presente'],
  ['💟', 'hearts', 'heart decoration', 'coracao decoracao'],
  ['♥️', 'hearts', 'heart suit', 'coracao naipe'],
  ['⭐', 'hearts', 'star', 'estrela'],
  ['🌟', 'hearts', 'glowing star', 'estrela brilhante'],
  ['✨', 'hearts', 'sparkles magic', 'brilhos magia'],
  ['💫', 'hearts', 'dizzy star swirl', 'estrela tonta'],
  ['🌠', 'hearts', 'shooting star', 'estrela cadente'],
  ['🔥', 'hearts', 'fire hot cool', 'fogo'],
  ['💥', 'hearts', 'boom explosion', 'explosao'],
  ['☄️', 'hearts', 'comet', 'cometa'],

  // --- Activities ---
  ['⚽', 'activities', 'soccer football ball', 'futebol bola'],
  ['🏀', 'activities', 'basketball', 'basquetebol'],
  ['🏈', 'activities', 'american football', 'futebol americano'],
  ['⚾', 'activities', 'baseball', 'basebol'],
  ['🎾', 'activities', 'tennis', 'tenis'],
  ['🏐', 'activities', 'volleyball', 'voleibol'],
  ['🏉', 'activities', 'rugby', 'rugby'],
  ['🎱', 'activities', 'pool billiards eight ball', 'bilhar'],
  ['🏓', 'activities', 'ping pong table tennis', 'ping pong tenis de mesa'],
  ['🏸', 'activities', 'badminton', 'badminton'],
  ['🥊', 'activities', 'boxing glove', 'boxe luva'],
  ['🥋', 'activities', 'martial arts karate', 'artes marciais karate'],
  ['🥅', 'activities', 'goal net', 'baliza rede'],
  ['⛳', 'activities', 'golf flag', 'golfe bandeira'],
  ['🏹', 'activities', 'archery bow arrow', 'arco e flecha'],
  ['🎣', 'activities', 'fishing rod', 'pesca cana'],
  ['🤿', 'activities', 'diving mask snorkel', 'mergulho mascara'],
  ['🎽', 'activities', 'running shirt race', 'camisola de corrida'],
  ['🛹', 'activities', 'skateboard', 'skate'],
  ['🛼', 'activities', 'roller skate', 'patins'],
  ['🛷', 'activities', 'sled sledge', 'treno'],
  ['⛸️', 'activities', 'ice skate', 'patinagem no gelo'],
  ['🎿', 'activities', 'skiing skis', 'esqui'],
  ['🏂', 'activities', 'snowboard', 'snowboard'],
  ['🪂', 'activities', 'parachute', 'paraquedas'],
  ['🏋️', 'activities', 'weightlifting gym', 'halterofilismo ginasio'],
  ['🤸', 'activities', 'cartwheel gymnastics', 'cambalhota ginastica'],
  ['🏄', 'activities', 'surfing surfboard', 'surf'],
  ['🏊', 'activities', 'swimming', 'natacao'],
  ['🚣', 'activities', 'rowing boat', 'remo barco'],
  ['🧗', 'activities', 'climbing', 'escalada'],
  ['🚴', 'activities', 'cycling bike', 'ciclismo bicicleta'],
  ['🏆', 'activities', 'trophy winner champion', 'trofeu vencedor campeao'],
  ['🥇', 'activities', 'gold medal first', 'medalha de ouro'],
  ['🥈', 'activities', 'silver medal second', 'medalha de prata'],
  ['🥉', 'activities', 'bronze medal third', 'medalha de bronze'],
  ['🎨', 'activities', 'art paint palette', 'arte pintura paleta'],
  ['🎬', 'activities', 'movie clapper film', 'filme claquete'],
  ['🎤', 'activities', 'microphone sing', 'microfone cantar'],
  ['🎧', 'activities', 'headphones music', 'auscultadores musica'],
  ['🎼', 'activities', 'music sheet', 'partitura musica'],
  ['🎹', 'activities', 'piano keyboard', 'piano teclado'],
  ['🎸', 'activities', 'guitar', 'guitarra'],
  ['🎻', 'activities', 'violin', 'violino'],
  ['🎲', 'activities', 'dice game', 'dado jogo'],
  ['🎯', 'activities', 'dart target bullseye', 'dardo alvo'],
  ['🎮', 'activities', 'video game controller', 'videojogo comando'],
  ['🧩', 'activities', 'puzzle piece', 'puzzle peca'],
  ['🪁', 'activities', 'kite', 'papagaio de papel'],

  // --- Nature ---
  ['🌸', 'nature', 'cherry blossom flower', 'flor de cerejeira'],
  ['💮', 'nature', 'white flower', 'flor branca'],
  ['🌹', 'nature', 'rose flower', 'rosa flor'],
  ['🌺', 'nature', 'hibiscus flower', 'flor hibisco'],
  ['🌻', 'nature', 'sunflower', 'girassol'],
  ['🌼', 'nature', 'daisy flower', 'margarida'],
  ['🌷', 'nature', 'tulip flower', 'tulipa'],
  ['🌱', 'nature', 'seedling sprout plant', 'rebento planta'],
  ['🪴', 'nature', 'potted plant', 'planta em vaso'],
  ['🌲', 'nature', 'evergreen tree', 'arvore pinheiro'],
  ['🌳', 'nature', 'deciduous tree', 'arvore'],
  ['🌴', 'nature', 'palm tree', 'palmeira'],
  ['🌵', 'nature', 'cactus', 'cato'],
  ['🌾', 'nature', 'wheat sheaf', 'trigo espiga'],
  ['☘️', 'nature', 'shamrock clover', 'trevo'],
  ['🍀', 'nature', 'four leaf clover lucky', 'trevo sorte'],
  ['🍁', 'nature', 'maple leaf autumn', 'folha outono'],
  ['🍂', 'nature', 'fallen leaves autumn', 'folhas caidas'],
  ['🍃', 'nature', 'leaves wind', 'folhas vento'],
  ['🍄', 'nature', 'mushroom', 'cogumelo'],
  ['🌍', 'nature', 'earth globe world', 'terra mundo'],
  ['🌎', 'nature', 'earth globe americas', 'terra globo'],
  ['🌏', 'nature', 'earth globe asia', 'terra globo'],
  ['🌐', 'nature', 'globe meridians world', 'globo mundo'],
  ['🌑', 'nature', 'new moon', 'lua nova'],
  ['🌕', 'nature', 'full moon', 'lua cheia'],
  ['🌙', 'nature', 'crescent moon', 'lua crescente'],
  ['🌚', 'nature', 'new moon face', 'lua com cara'],
  ['🌝', 'nature', 'full moon face', 'lua cheia com cara'],
  ['☀️', 'nature', 'sun sunny', 'sol'],
  ['🌤️', 'nature', 'sun behind small cloud', 'sol com nuvem'],
  ['⛅', 'nature', 'partly cloudy sun cloud', 'parcialmente nublado'],
  ['☁️', 'nature', 'cloud', 'nuvem'],
  ['🌦️', 'nature', 'sun behind rain cloud', 'sol e chuva'],
  ['🌧️', 'nature', 'rain cloud raining', 'nuvem de chuva'],
  ['⛈️', 'nature', 'thunderstorm lightning', 'trovoada'],
  ['🌩️', 'nature', 'cloud lightning', 'nuvem relampago'],
  ['🌨️', 'nature', 'snow cloud snowing', 'nuvem de neve'],
  ['❄️', 'nature', 'snowflake snow', 'floco de neve'],
  ['☃️', 'nature', 'snowman', 'boneco de neve'],
  ['⛄', 'nature', 'snowman no snow', 'boneco de neve'],
  ['🌬️', 'nature', 'wind blowing face air', 'vento'],
  ['💨', 'nature', 'dash wind fast', 'vento rapido'],
  ['💧', 'nature', 'droplet water drop', 'gota de agua'],
  ['☔', 'nature', 'umbrella rain', 'guarda chuva chuva'],
  ['🌊', 'nature', 'wave ocean sea', 'onda mar'],
  ['🌈', 'nature', 'rainbow', 'arco iris'],
  ['🪐', 'nature', 'planet saturn', 'planeta saturno'],
  ['⚡', 'nature', 'lightning bolt electric', 'relampago raio'],
]

export const EMOJIS = RAW_EMOJIS.map(([char, category, en, pt]) => ({
  char,
  category,
  en: en.split(' '),
  pt: pt.split(' '),
  keywords: `${en} ${pt}`,
}))

export const EMOJIS_BY_CATEGORY = EMOJI_CATEGORIES.reduce((acc, cat) => {
  acc[cat.id] = EMOJIS.filter((e) => e.category === cat.id)
  return acc
}, {})

// Strips accents so "cora" / "corac" / "coração" all match "coracao" -
// keyword data above is stored unaccented on purpose.
const foldAccents = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '')

// Matches a search/autocomplete query against each emoji's EN + PT keywords.
// Keyword-start matches (":gat" -> "gato") outrank mid-word matches, so the
// most likely intent surfaces first.
export function searchEmojis(query, limit = 8) {
  const q = foldAccents(query.trim().toLowerCase())
  if (!q) return []

  const startsWith = []
  const contains = []
  for (const emoji of EMOJIS) {
    const words = [...emoji.en, ...emoji.pt]
    if (words.some((w) => w.startsWith(q))) {
      startsWith.push(emoji)
    } else if (emoji.keywords.includes(q)) {
      contains.push(emoji)
    }
  }
  return [...startsWith, ...contains].slice(0, limit)
}
